name: Sync on DOM Cloud
on:
  workflow_dispatch: {} # Allows you to click a button to deploy manually
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.github/workflows/**' # Don't trigger if you only change this file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"source":"https://github.com/Megurian/wmsu-paynet.git","features":["mysql","php
            latest"],"nginx":{"root":"public_html/public","fastcgi":"on","locations":[{"match":"/","try_files":"$uri
            $uri/ /index.php$is_args$args"},{"match":"~
            \\.[^\\/]+(?<!\\.php)$","try_files":"$uri =404"}]},"commands":["(cp
            .env.example .env) || curl -sSLo .env
            https://raw.githubusercontent.com/laravel/laravel/refs/heads/12.x/.env.example","sed
            -ri \"s/APP_URL=.*/APP_URL=https:\\/\\/${DOMAIN}/g\" .env","sed -ri
            \"s/(# )?DB_CONNECTION=.*/DB_CONNECTION=mysql/g\" .env","sed -ri
            \"s/(# )?DB_HOST=.*/DB_HOST=localhost/g\" .env","sed -ri \"s/(#
            )?DB_PORT=.*/DB_PORT=3306/g\" .env","sed -ri \"s/(#
            )?DB_DATABASE=.*/DB_DATABASE=${DATABASE}/g\" .env","sed -ri \"s/(#
            )?DB_USERNAME=.*/DB_USERNAME=${USERNAME}/g\" .env","sed -ri \"s/(#
            )?DB_PASSWORD=.*/DB_PASSWORD=${MYPASSWD}/g\" .env","sed -ri
            \"s/LOG_STACK=single/LOG_STACK=daily,errorlog/g\" .env","sed -ri
            \"s/(# )?APP_DEBUG=.*/APP_DEBUG=true/g\" .env","composer
            install","find database -name \"*.sql\" -type f -exec sed -i
            's/utf8mb4_0900_ai_ci/utf8mb4_unicode_ci/g' {} \\; || true","php
            artisan migrate:fresh --seed || true","php artisan
            key:generate","php artisan storage:link","npm install","npm run
            build","chmod 0750 -R storage || true","rm -f public/hot"],"wait":1}
          verbose: true

      - name: Check deployment status
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploycheck
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
