name: Update Production on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {
              "source":"https://github.com/Megurian/wmsu-paynet.git",
              "features":["mysql","php latest"],
              "nginx":{
                "root":"public_html/public",
                "fastcgi":"on",
                "locations":[
                  {"match":"/","try_files":"$uri $uri/ /index.php$is_args$args"},
                  {"match":"~ \\.[^\\/]+(?<!\\.php)$","try_files":"$uri =404"}
                ]
              },
              "commands":[
                "(cp .env.example .env) || curl -sSLo .env https://raw.githubusercontent.com/laravel/laravel/refs/heads/12.x/.env.example",
                "sed -ri \"s/APP_URL=.*/APP_URL=https:\\/\\/${DOMAIN}/g\" .env",
                "sed -ri \"s/(# )?DB_CONNECTION=.*/DB_CONNECTION=mysql/g\" .env",
                "sed -ri \"s/(# )?DB_HOST=.*/DB_HOST=localhost/g\" .env",
                "sed -ri \"s/(# )?DB_PORT=.*/DB_PORT=3306/g\" .env",
                "sed -ri \"s/(# )?DB_DATABASE=.*/DB_DATABASE=${DATABASE}/g\" .env",
                "sed -ri \"s/(# )?DB_USERNAME=.*/DB_USERNAME=${USERNAME}/g\" .env",
                "sed -ri \"s/(# )?DB_PASSWORD=.*/DB_PASSWORD=${MYPASSWD}/g\" .env",
                "sed -ri \"s/LOG_STACK=single/LOG_STACK=daily,errorlog/g\" .env",
                "sed -ri \"s/(# )?APP_DEBUG=.*/APP_DEBUG=false/g\" .env",
                "sed -ri \"s/(# )?APP_ENV=.*/APP_ENV=production/g\" .env",
                "composer install --no-dev --optimize-autoloader --no-interaction",
                "find database -name \"*.sql\" -type f -exec sed -i 's/utf8mb4_0900_ai_ci/utf8mb4_unicode_ci/g' {} \\; || true",
                "php artisan migrate --force",
                "php artisan key:generate --force",
                "php artisan storage:link",
                "php artisan config:cache",
                "php artisan route:cache",
                "php artisan view:cache",
                "npm install",
                "npm run build",
                "chmod 0750 -R storage || true",
                "rm -f public/hot"
              ],
              "wait":1,
              "webhook_id":"Megurian/wmsu-paynet#95429d055acb3c980e34c20f94dbc6fe2ac77e21"
            }
          verbose: true
